# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false
install: true

services:
  postgresql
# Изменяет текущую временную зону.
before_install:
  - chmod +x mvnw
  - export TZ=Europe/Moscow
  - date
  - psql -c 'create database chat;' -U postgres
# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - roman9628@gmail.com
    on_success: never # default: change
    on_failure: always # default: always